:- multifile action/2.
:- multifile adjacent/4.
:- multifile canLock/2.
:- multifile canUnlock/2.
:- multifile connection/4.
:- multifile dark/1.
:- multifile description/4.
:- multifile dig/1.
:- multifile eat/1.
:- multifile enter/1.
:- multifile fakeDir/3.
:- multifile food/1.
:- multifile give/2.
:- multifile initial/2.
:- multifile initial/4.
:- multifile init_locked/1.
:- multifile init_state/1.
:- multifile init_unlocked/1.
:- multifile kick/1.
:- multifile kill/2.
:- multifile locked/1.
:- multifile look_at/1.
:- multifile picks_up/2.
:- multifile pick_up/1.
:- multifile purchased/1.
:- multifile put_down/1.
:- multifile random_statements/2.
:- multifile see/1.
:- multifile see_monster/1.
:- multifile see_object/1.
:- multifile see_person/1.
:- multifile sequential_statements/2.
:- multifile talk_to/1.
:- multifile toss/2.
:- multifile unlock/1.
:- multifile wanders/2.
:- multifile wares/2.
:- multifile weapon/1.
:- multifile words/2.
:- multifile writeable/4.
